// src/Home/Home.tsx
import { ProductCard } from "./ProductCard";
import { useProducts } from "./useProducts";

interface HomeProps {
  useProductsHook?: () => Pick<
    ReturnType<typeof useProducts>,
    "categories" | "isLoading" | "error"
  >;
}

export const Home = ({ useProductsHook = useProducts }: HomeProps) => {
  const { categories, isLoading, error } = useProductsHook();
  if (isLoading) {
    return <>Loading...</>;
  }

  if (error) {
    return <>Error</>;
  }
  return (
    <>
      {categories.map((category) => (
        <section
          className="nes-container with-title showcase"
          key={category.name}
        >
          <h2 className="title">{category.name}</h2>
          <section className="items">
            {category.items.map((item) => (
              <ProductCard key={item.name} datum={item} />
            ))}
          </section>
        </section>
      ))}
    </>
  );
};

// src/Home/Home.vue
<template>
    <template v-if="isLoading">
        Loading...
    </template>
    <template v-else-if="error">
        Error
    </template>
    <template v-else>
        <section v-for="{ name, items } in categories" :key="name" class="nes-container with-title showcase">
            <h2 class="title">{{ name }}</h2>
            <section class="items">
                <ProductCard v-for="item in items" :key="item.name" :datum="item" />
            </section>
        </section>
    </template>
</template>

<script setup lang="ts">
import ProductCard from './ProductCard.vue';
import { useProducts } from './useProducts';

const { categories, error, isLoading } = useProducts()

</script>

<style scoped>
</style>
